<?php

return [
    'roles' => [
        'owner' => [
            'view-customers',
            'create-customer',
            'edit-customer',
            'delete-customer',
            'view-products',
            'create-product',
            'edit-product',
            'delete-product',
            'view-documents',
            'create-document',
            'edit-document',
            'delete-document',
            'finalize-document',
            'sign-document',
            'view-tva-report',
            'close-period',
            'invite-users',
            'view-settings',
            'manage-recurring-invoices',
            'manage-subscription',
        ],
        'manager' => [
            'view-customers',
            'create-customer',
            'edit-customer',
            'delete-customer',
            'view-products',
            'create-product',
            'edit-product',
            'delete-product',
            'view-documents',
            'create-document',
            'edit-document',
            'delete-document',
            'finalize-document',
            'sign-document',
            'invite-users',
            'view-settings',
            'manage-recurring-invoices',
        ],
        'accountant' => [
            'view-customers',
            'view-products',
            'view-documents',
            'finalize-document',
            'view-tva-report',
            'close-period',
        ],
        'viewer' => [
            'view-customers',
            'view-products',
            'view-documents',
            'view-tva-report',
            'view-settings',
        ],
    ],
];
